### ISSUE TITLE
--username option does not work

### ISSUE THREAD

**Issue by wkentaro** [juanpabloaj/slacker-cli#15]

**Comment by wkentaro** [comment]
@tomasv
See also: #14 , https://github.com/juanpabloaj/slacker-cli/pull/14#issuecomment-136959150

**NOT WORK**
it does not work actually, if --as-user option is set, it raises error  and no message in the slack channel

```
% date | slacker -u hubot -a wkentaro
Traceback (most recent call last):
  File "/usr/local/bin/slacker", line 9, in <module>
    load_entry_point('slacker-cli==0.2.1', 'console_scripts', 'slacker')()
  File "/usr/local/lib/python2.7/dist-packages/slacker_cli/__init__.py", line 94, in main
    post_message(token, '@' + user, message, name, as_user, icon)
  File "/usr/local/lib/python2.7/dist-packages/slacker_cli/__init__.py", line 19, in post_message
    as_user=as_user, icon_emoji=icon)
  File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 257, in post_message
    'icon_emoji': icon_emoji
  File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 69, in post
    return self._request(requests.post, api, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 61, in _request
    raise Error(response.error)
slacker.Error: not_in_channel
```

no --as-user option, no error and no message in the slack channel
```
% date | slacker -u hubot
```

**ONLY WORKS**
sending message myself does work, the message will be appear at @slackbot channel.
```
% date | slacker -u wkentaro
```
