### ISSUE TITLE
WantWriteError

### ISSUE THREAD

**Issue by timbremer** [juanpabloaj/slacker-cli#25]
Hi! I'm using Slacker CLI for the first time and currently run into this error. No idea what the cause could be, maybe it isn't able to find the file?

`$ slacker -c ******* -n ****** -f app/build/outputs/apk/app-beta-debug.apk -i https://**********
Traceback (most recent call last):
  File "/usr/local/bin/slacker", line 9, in <module>
    load_entry_point('slacker-cli==0.2.7', 'console_scripts', 'slacker')()
  File "/usr/local/lib/python2.7/dist-packages/slacker_cli/__init__.py", line 157, in main
    upload_file(token, channel, file_name)
  File "/usr/local/lib/python2.7/dist-packages/slacker_cli/__init__.py", line 73, in upload_file
    slack.files.upload(file_name, channels=channel_id)
  File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 469, in upload
    files={'file': f})
  File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 71, in post
    return self._request(requests.post, api, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 57, in _request
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 855, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 977, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 849, in _raise_ssl_error
    raise WantWriteError()
OpenSSL.SSL.WantWriteError`

(Error code is bady formatted, sorry for that.)

**Comment by timbremer** [comment]
Message was empty.
Fix: `echo | slacker ...`
