### ISSUE TITLE
Coveralls is out of date

### ISSUE THREAD

**Issue by hugovk** [juanpabloaj/slacker-cli#29]
The last run is from 08 Sep 2015:
https://coveralls.io/github/juanpabloaj/slacker-cli

Because:
```
$ coveralls --verbose
Missing .coveralls.yml file. Using only env variables.
Submitting coverage to coveralls.io...
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/bin/coveralls", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/cli.py", line 49, in main
    result = coverallz.wear()
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/api.py", line 73, in wear
    data = self.create_data()
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/api.py", line 122, in create_data
    self._data = {'source_files': self.get_coverage()}
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/api.py", line 130, in get_coverage
    workman._harvest_data()
AttributeError: 'Coverage' object has no attribute '_harvest_data'
```
https://travis-ci.org/juanpabloaj/slacker-cli/jobs/197408045#L200

**Comment by juanpabloaj** [comment]
😮  thanks @hugovk I try to fix
